### ISSUE TITLE
byte index 4 is out of bounds of ` `

### ISSUE THREAD

**Issue by zhiburt** [nushell/reedline#513]
I was playing a bit with this,
But not sure whether it's a bug or I did something wrong.

Describe the problem you are observing.

## Steps to reproduce
1. minimal posssible steps necessary

```rust
        use reedline::{
            default_emacs_keybindings, ColumnarMenu, DefaultCompleter, DefaultPrompt, Emacs,
            ExampleHighlighter, FileBackedHistory, KeyCode, KeyModifiers, ListMenu, Reedline,
            ReedlineEvent, ReedlineMenu, Signal,
        };

        let history = Box::new(
            FileBackedHistory::with_file(5, "asda.txt".into())
                .expect("Error configuring history with file"),
        );

        let commands = vec![
            "test".into(),
            "hello world".into(),
            "hello world reedline".into(),
            "this is the reedline crate".into(),
        ];
        let completer = Box::new(DefaultCompleter::new_with_wordlen(commands.clone(), 2));
        // Use the interactive menu to select options from the completer
        let completion_menu = Box::new(ListMenu::default().with_name("completion_menu"));
        // Set up the required keybindings
        let mut keybindings = default_emacs_keybindings();
        keybindings.add_binding(
            KeyModifiers::NONE,
            KeyCode::Tab,
            ReedlineEvent::UntilFound(vec![
                ReedlineEvent::Menu("completion_menu".to_string()),
                ReedlineEvent::MenuNext,
            ]),
        );

        let edit_mode = Box::new(Emacs::new(keybindings));

        let highlighter = Box::new(ExampleHighlighter::new(commands));

        let mut line_editor = Reedline::create()
            .with_completer(completer)
            .with_menu(ReedlineMenu::EngineCompleter(completion_menu))
            .with_edit_mode(edit_mode)
            .with_highlighter(highlighter)
            .with_history(history);

        let prompt = DefaultPrompt::default();

        loop {
            let sig = line_editor.read_line(&prompt);
            match sig {
                Ok(Signal::Success(buffer)) => {
                    println!("We processed: {}", buffer);
                }
                Ok(Signal::CtrlD) | Ok(Signal::CtrlC) => {
                    println!("\nAborted!");
                    break;
                }
                x => {
                    println!("Event: {:?}", x);
                }
            }
        }

```

3. to cause the problem

      1. Type `test`
      2. Press `TAB`
      3. Press `SPACE`

## Screenshots/Screencaptures

```log
~/bin/nushell? testthread 'main' panicked at 'byte index 4 is out of bounds of ` `', library/core/src/str/mod.rs:107:9                                           11/13/2022 08:30:29 PM
stack backtrace:0 - 0  total: 0  
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::str::slice_error_fail_rt
   3: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
   4: core::intrinsics::const_eval_select
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/intrinsics.rs:2376:5
   5: core::str::slice_error_fail
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/str/mod.rs:86:9
   6: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/str/traits.rs:218:21
   7: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/str/traits.rs:65:9
   8: <reedline::completion::default::DefaultCompleter as reedline::completion::base::Completer>::complete
             at /home/maxim/.cargo/git/checkouts/reedline-e42026a78d91c510/39e6bc8/src/completion/default.rs:75:32
   9: <reedline::menu::list_menu::ListMenu as reedline::menu::Menu>::update_values
             at /home/maxim/.cargo/git/checkouts/reedline-e42026a78d91c510/39e6bc8/src/menu/list_menu.rs:437:13
  10: <reedline::menu::list_menu::ListMenu as reedline::menu::Menu>::update_working_details
             at /home/maxim/.cargo/git/checkouts/reedline-e42026a78d91c510/39e6bc8/src/menu/list_menu.rs:522:21
  11: reedline::menu::ReedlineMenu::update_working_details
             at /home/maxim/.cargo/git/checkouts/reedline-e42026a78d91c510/39e6bc8/src/menu/mod.rs:208:17
  12: reedline::engine::Reedline::buffer_paint
             at /home/maxim/.cargo/git/checkouts/reedline-e42026a78d91c510/39e6bc8/src/engine.rs:1450:17
  13: reedline::engine::Reedline::repaint
             at /home/maxim/.cargo/git/checkouts/reedline-e42026a78d91c510/39e6bc8/src/engine.rs:1226:13
  14: reedline::engine::Reedline::read_line_helper
             at /home/maxim/.cargo/git/checkouts/reedline-e42026a78d91c510/39e6bc8/src/engine.rs:571:29
  15: reedline::engine::Reedline::read_line
             at /home/maxim/.cargo/git/checkouts/reedline-e42026a78d91c510/39e6bc8/src/engine.rs:440:22
  16: <nu_command::viewers::scroll::Scroll as nu_protocol::engine::command::Command>::run
             at ./crates/nu-command/src/viewers/scroll/mod.rs:107:23
  17: nu_engine::eval::eval_call
             at ./crates/nu-engine/src/eval.rs:170:9
  18: nu_engine::eval::eval_expression_with_input
             at ./crates/nu-engine/src/eval.rs:651:25
  19: nu_engine::eval::eval_block
             at ./crates/nu-engine/src/eval.rs:780:31
  20: nu_cli::util::eval_source
             at ./crates/nu-cli/src/util.rs:233:11
  21: nu_cli::repl::evaluate_repl
             at ./crates/nu-cli/src/repl.rs:438:21
  22: nu::main
             at ./src/main.rs:438:31
  23: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sholderbach** [comment]
Thanks for the repro, I had a report that was hard to track down previously.

Quick question, the code shown is the minimal example the backtrace is from nu?

**Comment by zhiburt** [comment]
> Quick question, the code shown is the minimal example the backtrace is from nu?

negative

**Comment by ClementNerma** [comment]
Any news on this? I'm encoutering the same issue right now :/
On my side it only happens with `ListMenu`, not `ColumnarMenu`, for some reason...

**Comment by kronberger-droid** [comment]
Not reproducible anymore
